# Generated by Django 4.2.23 on 2025-07-21 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('therapist', 'Терапевт'), ('surgeon', 'Хірург'), ('orthodontist', 'Ортодонт'), ('prosthodontist', 'Ортопед'), ('periodontist', 'Пародонтолог'), ('endodontist', 'Ендодонтист')], max_length=30)),
                ('biography', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dentist_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
